### ISSUE TITLE
Semi colon ; in query

### ISSUE THREAD

**Issue by rizwan-ishtiaq** [BernhardSchlegel/SQL-dumper#4]
### Problem
sqldump.etl.Query replacing ; with empty string while loading queries from file. (see line 60)

This will case the problem for some case for example below query
```
with temp as ( SELECT 'value1;value2;value3' text FROM  dual )
select regexp_substr(t.text, '[^;]+', 1, levels.column_value) as text from temp t,
	table(cast(multiset(select level from dual connect by level <= length (regexp_replace(t.text, '[^;]+')) + 1) as sys.OdciNumberList)) levels
```
### Possible solution:
1. Should not replace the ; (ask in documentation/readme to not put semi-colon in file)
2. Remove only the last ; from query (in the end of file)

**Comment by BernhardSchlegel** [comment]
Hi there, 

thanks for reaching out and many thanks for the solutions. I'd go for the second one since that poses fewer restrictions (and reading the readme requirements) in comparision to the first one. 

If you want to submit a PR you are very welcome to do so. I'll update the code as soon as I have time otherwise.

Cheers

**Comment by rizwan-ishtiaq** [comment]
I have created pull request. Also closing the issue

**Comment by BernhardSchlegel** [comment]
cool, thanks-a-lot! merged.
